baseURL = "https://RhymeJewel.github.io/"
title   = "RhymeJewel"
theme   = "PaperMod"
enableRobotsTXT = true
[pagination]
pagerSize = 10
[params.profileMode]
  enabled    = true
  subtitle   = "Computational toxicology & risk assessment"
  title      = "Yun's Blog"
  imageUrl   = "/static/images/avatar.jpg"   # put your image in static/images/avatar.jpg
  imageTitle = "Yun Zhou"
  [[params.profileMode.buttons]]
    name = "Contact"
    url  = "/contact/"
  [[params.profileMode.buttons]]
  name = "About"
  url  = "/about/"
  
[menu]
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
  identifier = "miscellaneous"
  name = "Miscellaneous"
  url = "/miscellaneous/"
  weight = 30  

