baseURL = "https://RhymeJewel.github.io/"
title   = "RhymeJewel"
theme   = "PaperMod"
enableRobotsTXT = true
[pagination]
pagerSize = 10
[params.profileMode]
  enabled    = true
  title      = "Yun's Blog"
  subtitle   = "Computational toxicology & risk assessment"
  subTitle   = "Computational toxicology & risk assessment"
  imageUrl   = "/images/avatar.jpg"   # put your image in static/images/avatar.jpg
  imageTitle = "Yun Zhou"
  [[params.profileMode.buttons]]
    name = "About"
    url  = "/about/"
  [[params.profileMode.buttons]]
    name = "Contact"
    url  = "/contact/"

  
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10
  [[menu.main]]
    identifier = "mosaic thinking"
    name = "Mosaic Thinking"
    url = "/mosaic thinking/"
    weight = 20
  [[menu.main]]
  identifier = "miscellaneous"
  name = "Miscellaneous"
  url = "/miscellaneous/"
  weight = 30  

